### PR TITLE
Create adoption-plan.md

### PR DESCRIPTION
**Pull request by Danajoyluck**

### CODE REVIEW

**Comment by Danajoyluck** [comment]
The plan for tracking the adoption of the security baseline by pilot projects, including the projects' current state.

**Comment by eddie-knight** [comment]
@Danajoyluck how do you feel about moving this plan into GitHub issues that can be organized into a project board?

**Comment by Danajoyluck** [comment]
> @Danajoyluck how do you feel about moving this plan into GitHub issues that can be organized into a project board?

sure! could you please take the lead? I will learn the how from you!

**Comment by eddie-knight** [comment]
Sure thing!

**Comment by eddie-knight** [comment]
@Danajoyluck What do you think of this as a starter?

https://github.com/orgs/ossf/projects/26/views/1

I added some basic tasks with start/end dates and sorted them out in an aggressive timeline that contains a slippage buffer prior to the large November rollout.

**Comment by Danajoyluck** [comment]
Thanks a lot @eddie-knight for the detailed planning. I like the plan and it will work well for the full adoption across OpenSSF and LF piloting. I feel for the 9/15 pilot adoption, the timeline may not work. (See the [tracking so far](https://docs.google.com/spreadsheets/d/1LCLpN1Hgx7C9M9KNuvH5aN5vukYPmxrq_1dUQrDhnco/edit?gid=1170578288#gid=1170578288)) How about we go with the tracking plan for now so that we can take immediate actions, then leverage your long term plan once we have more comprehensive metrics defined?

**Comment by eddie-knight** [comment]
@Danajoyluck I'm trying to understand your feeling regarding the timeline. Are you wanting to move up the OpenSSF pilot to happen simultaneously with the metrics refinement?

**Review by SecurityCRob — APPROVED** [review]

**Review by puerco — APPROVED** [review]
Looks good to me with my maintainer hat on :rocket:

**Pull request merged**
